# Generated by Django 2.0.1 on 2018-02-07 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Password_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.TextField()),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.TextField()),
                ('sessionKey', models.CharField(max_length=20)),
                ('keyHolderIP', models.CharField(max_length=50)),
                ('timeStamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='password_data',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sifre.Platform'),
        ),
        migrations.AddField(
            model_name='password_data',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sifre.Person'),
        ),
    ]
